# Generated by Django 4.2.6 on 2023-10-30 21:07

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Kindle", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapeInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_scraped", models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name="highlight",
            name="last_accessed",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
